create database radioadok;
use database radioadok

create table kiosztas
(
    azon int unsigned not null auto_increment primary key,
    frekvencia float,
    teljesitmeny float,
    csatorna varchar(150),
    adohely varchar(150),
    cim varchar(150)
);

create table telepules
(
    nev varchar(150) primary key references kiosztas(adohely) on delete cascade,
    megye varchar(150)
);

create table regio
(
    nev varchar(150),
    megye varchar(150) primary key references telepules(megye) on delete cascade
);

insert into telepules(nev, megye) values
('Aba', 'Fejér'),
('Abádszalók', 'Jász-Nagykun-Szolnok'),
('Abaújszántó', 'Borsod-Abaúj-Zemplén'),
('Abony', 'Pest'),
('Ács', 'Komárom-Esztergom'),
('Adony', 'Fejér'),
('Aggtelek', 'Borsod-Abaúj-Zemplén'),
('Ajak', 'Szabolcs-Szatmár-Bereg'),
('Ajka', 'Veszprém'),
('Albertirsa', 'Pest'),
('Algyő', 'Csongrád'),
('Alsónémedi', 'Pest'),
('Alsózsolca', 'Borsod-Abaúj-Zemplén'),
('Áporka', 'Pest'),
('Arló', 'Borsod-Abaúj-Zemplén'),
('Aszaló', 'Borsod-Abaúj-Zemplén'),
('Aszód', 'Pest'),
('Bábolna', 'Komárom-Esztergom'),
('Bácsalmás', 'Bács-Kiskun'),
('Bácsbokod', 'Bács-Kiskun'),
('Badacsonytomaj', 'Veszprém'),
('Bag', 'Pest'),
('Bagamér', 'Hajdú-Bihar'),
('Baja', 'Bács-Kiskun'),
('Baktalórántháza', 'Szabolcs-Szatmár-Bereg'),
('Balassagyarmat', 'Nógrád'),
('Balatonalmádi', 'Veszprém'),
('Balatonboglár', 'Somogy'),
('Balatonföldvár', 'Somogy'),
('Balatonfüred', 'Veszprém'),
('Balatonfűzfő', 'Veszprém'),
('Balatonkenese', 'Veszprém'),
('Balatonlelle', 'Somogy'),
('Balatonszárszó', 'Somogy'),
('Balkány', 'Szabolcs-Szatmár-Bereg'),
('Balmazújváros', 'Hajdú-Bihar'),
('Barcs', 'Somogy'),
('Bátaszék', 'Tolna'),
('Bátonyterenye', 'Nógrád'),
('Battonya', 'Békés'),
('Békés', 'Békés'),
('Békéscsaba', 'Békés'),
('Békésszentandrás', 'Békés'),
('Bélapátfalva', 'Heves'),
('Beled', 'Győr-Moson-Sopron'),
('Beremend', 'Baranya'),
('Berettyóújfalu', 'Hajdú-Bihar'),
('Berhida', 'Veszprém'),
('Berzence', 'Somogy'),
('Biatorbágy', 'Pest'),
('Bicske', 'Fejér'),
('Biharkeresztes', 'Hajdú-Bihar'),
('Bodajk', 'Fejér'),
('Bóly', 'Baranya'),
('Bonyhád', 'Tolna'),
('Borsodnádasd', 'Borsod-Abaúj-Zemplén'),
('Bősárkány', 'Győr-Moson-Sopron'),
('Budakalász', 'Pest'),
('Budakeszi', 'Pest'),
('Budaörs', 'Pest'),
('Budapest', 'Budapest'),
('Bugac', 'Bács-Kiskun'),
('Bugyi', 'Pest'),
('Bük', 'Vas'),
('Cece', 'Fejér'),
('Cegléd', 'Pest'),
('Celldömölk', 'Vas'),
('Cibakháza', 'Jász-Nagykun-Szolnok'),
('Cigánd', 'Borsod-Abaúj-Zemplén'),
('Csabacsűd', 'Békés'),
('Csákvár', 'Fejér'),
('Csanádpalota', 'Csongrád'),
('Csávoly', 'Bács-Kiskun'),
('Csenger', 'Szabolcs-Szatmár-Bereg'),
('Csengőd', 'Bács-Kiskun'),
('Csepreg', 'Vas'),
('Csobánka', 'Pest'),
('Csongrád', 'Csongrád'),
('Csorna', 'Győr-Moson-Sopron'),
('Csorvás', 'Békés'),
('Csökmő', 'Hajdú-Bihar'),
('Csömör', 'Pest'),
('Csurgó', 'Somogy'),
('Dabas', 'Pest'),
('Debrecen', 'Hajdú-Bihar'),
('Decs', 'Tolna'),
('Demecser', 'Szabolcs-Szatmár-Bereg'),
('Derecske', 'Hajdú-Bihar'),
('Dévaványa', 'Békés'),
('Devecser', 'Veszprém'),
('Doboz', 'Békés'),
('Dombegyház', 'Békés'),
('Dombóvár', 'Tolna'),
('Dombrád', 'Szabolcs-Szatmár-Bereg'),
('Dorog', 'Komárom-Esztergom'),
('Dömös', 'Komárom-Esztergom'),
('Dömsöd', 'Pest'),
('Dunaföldvár', 'Tolna'),
('Dunaharaszti', 'Pest'),
('Dunakeszi', 'Pest'),
('Dunapataj', 'Bács-Kiskun'),
('Dunaújváros', 'Fejér'),
('Dunavarsány', 'Pest'),
('Dunavecse', 'Bács-Kiskun'),
('Edelény', 'Borsod-Abaúj-Zemplén'),
('Eger', 'Heves'),
('Egyek', 'Hajdú-Bihar'),
('Elek', 'Békés'),
('Előszállás', 'Fejér'),
('Emőd', 'Borsod-Abaúj-Zemplén'),
('Encs', 'Borsod-Abaúj-Zemplén'),
('Enying', 'Fejér'),
('Ercsi', 'Fejér'),
('Érd', 'Pest'),
('Erdőkertes', 'Pest'),
('Esztergom', 'Komárom-Esztergom'),
('Etyek', 'Fejér'),
('Fadd', 'Tolna'),
('Fegyvernek', 'Jász-Nagykun-Szolnok'),
('Fehérgyarmat', 'Szabolcs-Szatmár-Bereg'),
('Felsőszölnök', 'Vas'),
('Felsőzsolca', 'Borsod-Abaúj-Zemplén'),
('Fertőd', 'Győr-Moson-Sopron'),
('Fertőszentmiklós', 'Győr-Moson-Sopron'),
('Fonyód', 'Somogy'),
('Fót', 'Pest'),
('Földes', 'Hajdú-Bihar'),
('Füzesabony', 'Heves'),
('Füzesgyarmat', 'Békés'),
('Gádoros', 'Békés'),
('Gárdony', 'Fejér'),
('Gávavencsellő', 'Szabolcs-Szatmár-Bereg'),
('Gerecse', 'Komárom-Esztergom'),
('Göd', 'Pest'),
('Gödöllő', 'Pest'),
('Gönc', 'Borsod-Abaúj-Zemplén'),
('Gyál', 'Pest'),
('Gyenesdiás', 'Zala'),
('Gyomaendrőd', 'Békés'),
('Gyömrő', 'Pest'),
('Gyöngyös', 'Heves'),
('Gyönk', 'Tolna'),
('Győr', 'Győr-Moson-Sopron'),
('Gyula', 'Békés'),
('Hajdúböszörmény', 'Hajdú-Bihar'),
('Hajdúdorog', 'Hajdú-Bihar'),
('Hajdúhadház', 'Hajdú-Bihar'),
('Hajdúnánás', 'Hajdú-Bihar'),
('Hajdúsámson', 'Hajdú-Bihar'),
('Hajdúszoboszló', 'Hajdú-Bihar'),
('Hajós', 'Bács-Kiskun'),
('Halásztelek', 'Pest'),
('Harkány', 'Baranya'),
('Harta', 'Bács-Kiskun'),
('Hatvan', 'Heves'),
('Hegyeshalom', 'Győr-Moson-Sopron'),
('Herend', 'Veszprém'),
('Heves', 'Heves'),
('Hévíz', 'Zala'),
('Hodász', 'Szabolcs-Szatmár-Bereg'),
('Hódmezővásárhely', 'Csongrád'),
('Hosszúpályi', 'Hajdú-Bihar'),
('Hőgyész', 'Tolna'),
('Ibrány', 'Szabolcs-Szatmár-Bereg'),
('Igal', 'Somogy'),
('Isaszeg', 'Pest'),
('Izsák', 'Bács-Kiskun'),
('Izsófalva', 'Borsod-Abaúj-Zemplén'),
('Jánoshalma', 'Bács-Kiskun'),
('Jánosháza', 'Vas'),
('Jánossomorja', 'Győr-Moson-Sopron'),
('Jászapáti', 'Jász-Nagykun-Szolnok'),
('Jászárokszállás', 'Jász-Nagykun-Szolnok'),
('Jászberény', 'Jász-Nagykun-Szolnok'),
('Jászfényszaru', 'Jász-Nagykun-Szolnok'),
('Jászkisér', 'Jász-Nagykun-Szolnok'),
('Jászladány', 'Jász-Nagykun-Szolnok'),
('Kaba', 'Hajdú-Bihar'),
('Kab-hegy', 'Veszprém'),
('Kadarkút', 'Somogy'),
('Kál', 'Heves'),
('Kállósemjén', 'Szabolcs-Szatmár-Bereg'),
('Kalocsa', 'Bács-Kiskun'),
('Kaposvár', 'Somogy'),
('Kapuvár', 'Győr-Moson-Sopron'),
('Karcag', 'Jász-Nagykun-Szolnok'),
('Kartal', 'Pest'),
('Kazincbarcika', 'Borsod-Abaúj-Zemplén'),
('Kecel', 'Bács-Kiskun'),
('Kecskemét', 'Bács-Kiskun'),
('Kékes', 'Heves'),
('Kemecse', 'Szabolcs-Szatmár-Bereg'),
('Kenderes', 'Jász-Nagykun-Szolnok'),
('Kerekegyháza', 'Bács-Kiskun'),
('Kerepes', 'Pest'),
('Keszthely', 'Zala'),
('Kétegyháza', 'Békés'),
('Kevermes', 'Békés'),
('Kisbér', 'Komárom-Esztergom'),
('Kisköre', 'Heves'),
('Kiskőrös', 'Bács-Kiskun'),
('Kiskunfélegyháza', 'Bács-Kiskun'),
('Kiskunhalas', 'Bács-Kiskun'),
('Kiskunlacháza', 'Pest'),
('Kiskunmajsa', 'Bács-Kiskun'),
('Kistarcsa', 'Pest'),
('Kistelek', 'Csongrád'),
('Kisújszállás', 'Jász-Nagykun-Szolnok'),
('Kisvárda', 'Szabolcs-Szatmár-Bereg'),
('Komádi', 'Hajdú-Bihar'),
('Komárom', 'Komárom-Esztergom'),
('Komló', 'Baranya'),
('Kondoros', 'Békés'),
('Kozármisleny', 'Baranya'),
('Kölcse', 'Szabolcs-Szatmár-Bereg'),
('Körmend', 'Vas'),
('Körösladány', 'Békés'),
('Kőszeg', 'Vas'),
('Kunhegyes', 'Jász-Nagykun-Szolnok'),
('Kunmadaras', 'Jász-Nagykun-Szolnok'),
('Kunszentmárton', 'Jász-Nagykun-Szolnok'),
('Kunszentmiklós', 'Bács-Kiskun'),
('Lábatlan', 'Komárom-Esztergom'),
('Lajoskomárom', 'Fejér'),
('Lajosmizse', 'Bács-Kiskun'),
('Lakitelek', 'Bács-Kiskun'),
('Leányfalu', 'Pest'),
('Lébény', 'Győr-Moson-Sopron'),
('Lengyeltóti', 'Somogy'),
('Lenti', 'Zala'),
('Lepsény', 'Fejér'),
('Létavértes', 'Hajdú-Bihar'),
('Letenye', 'Zala'),
('Levelek', 'Szabolcs-Szatmár-Bereg'),
('Lőrinci', 'Heves'),
('Maglód', 'Pest'),
('Mágocs', 'Baranya'),
('Makó', 'Csongrád'),
('Mándok', 'Szabolcs-Szatmár-Bereg'),
('Marcali', 'Somogy'),
('Máriapócs', 'Szabolcs-Szatmár-Bereg'),
('Mártély', 'Csongrád'),
('Martfű', 'Jász-Nagykun-Szolnok'),
('Martonvásár', 'Fejér'),
('Mátészalka', 'Szabolcs-Szatmár-Bereg'),
('Medgyesegyháza', 'Békés'),
('Mélykút', 'Bács-Kiskun'),
('Mérk', 'Szabolcs-Szatmár-Bereg'),
('Mezőberény', 'Békés'),
('Mezőcsát', 'Borsod-Abaúj-Zemplén'),
('Mezőfalva', 'Fejér'),
('Mezőhegyes', 'Békés'),
('Mezőkeresztes', 'Borsod-Abaúj-Zemplén'),
('Mezőkovácsháza', 'Békés'),
('Mezőkövesd', 'Borsod-Abaúj-Zemplén'),
('Mezőtúr', 'Jász-Nagykun-Szolnok'),
('Mindszent', 'Csongrád'),
('Miskolc', 'Borsod-Abaúj-Zemplén'),
('Mogyoród', 'Pest'),
('Mohács', 'Baranya'),
('Monor', 'Pest'),
('Mór', 'Fejér'),
('Mórahalom', 'Csongrád'),
('Mosonmagyaróvár', 'Győr-Moson-Sopron'),
('Múcsony', 'Borsod-Abaúj-Zemplén'),
('Nádudvar', 'Hajdú-Bihar'),
('Nagyatád', 'Somogy'),
('Nagybajom', 'Somogy'),
('Nagycenk', 'Győr-Moson-Sopron'),
('Nagydorog', 'Tolna'),
('Nagyecsed', 'Szabolcs-Szatmár-Bereg'),
('Nagyhalász', 'Szabolcs-Szatmár-Bereg'),
('Nagyigmánd', 'Komárom-Esztergom'),
('Nagykálló', 'Szabolcs-Szatmár-Bereg'),
('Nagykanizsa', 'Zala'),
('Nagykáta', 'Pest'),
('Nagykovácsi', 'Pest'),
('Nagykőrös', 'Pest'),
('Nagymágocs', 'Csongrád'),
('Nagymányok', 'Tolna'),
('Nagymaros', 'Pest'),
('Nagyrábé', 'Hajdú-Bihar'),
('Nagyszénás', 'Békés'),
('Nyékládháza', 'Borsod-Abaúj-Zemplén'),
('Nyergesújfalu', 'Komárom-Esztergom'),
('Nyírábrány', 'Hajdú-Bihar'),
('Nyíradony', 'Hajdú-Bihar'),
('Nyírbátor', 'Szabolcs-Szatmár-Bereg'),
('Nyírbéltek', 'Szabolcs-Szatmár-Bereg'),
('Nyírbogát', 'Szabolcs-Szatmár-Bereg'),
('Nyíregyháza', 'Szabolcs-Szatmár-Bereg'),
('Nyírlugos', 'Szabolcs-Szatmár-Bereg'),
('Nyírmada', 'Szabolcs-Szatmár-Bereg'),
('Nyírtelek', 'Szabolcs-Szatmár-Bereg'),
('Ócsa', 'Pest'),
('Onga', 'Borsod-Abaúj-Zemplén'),
('Orosháza', 'Békés'),
('Oroszlány', 'Komárom-Esztergom'),
('Ózd', 'Borsod-Abaúj-Zemplén'),
('Öcsöd', 'Jász-Nagykun-Szolnok'),
('Ököritófülpös', 'Szabolcs-Szatmár-Bereg'),
('Őrbottyán', 'Pest'),
('Őriszentpéter', 'Vas'),
('Örkény', 'Pest'),
('Pacsa', 'Zala'),
('Paks', 'Tolna'),
('Pálháza', 'Borsod-Abaúj-Zemplén'),
('Pannonhalma', 'Győr-Moson-Sopron'),
('Pápa', 'Veszprém'),
('Parád', 'Heves'),
('Pásztó', 'Nógrád'),
('Pécel', 'Pest'),
('Pécs', 'Baranya'),
('Pécsvárad', 'Baranya'),
('Perkáta', 'Fejér'),
('Pétervására', 'Heves'),
('Pétfürdő', 'Veszprém'),
('Pilis', 'Pest'),
('Piliscsaba', 'Pest'),
('Pilisvörösvár', 'Pest'),
('Pincehely', 'Tolna'),
('Pocsaj', 'Hajdú-Bihar'),
('Polgár', 'Hajdú-Bihar'),
('Polgárdi', 'Fejér'),
('Pomáz', 'Pest'),
('Porcsalma', 'Szabolcs-Szatmár-Bereg'),
('Pusztaszabolcs', 'Fejér'),
('Putnok', 'Borsod-Abaúj-Zemplén'),
('Püspökladány', 'Hajdú-Bihar'),
('Rábaszentandrás', 'Győr-Moson-Sopron'),
('Rácalmás', 'Fejér'),
('Ráckeve', 'Pest'),
('Rakamaz', 'Szabolcs-Szatmár-Bereg'),
('Rákóczifalva', 'Jász-Nagykun-Szolnok'),
('Recsk', 'Heves'),
('Répcelak', 'Vas'),
('Rétság', 'Nógrád'),
('Révfülöp', 'Veszprém'),
('Ricse', 'Borsod-Abaúj-Zemplén'),
('Rudabánya', 'Borsod-Abaúj-Zemplén'),
('Sajóbábony', 'Borsod-Abaúj-Zemplén'),
('Sajószentpéter', 'Borsod-Abaúj-Zemplén'),
('Salgótarján', 'Nógrád'),
('Sándorfalva', 'Csongrád'),
('Sárbogárd', 'Fejér'),
('Sarkad', 'Békés'),
('Sárosd', 'Fejér'),
('Sárospatak', 'Borsod-Abaúj-Zemplén'),
('Sárrétudvari', 'Hajdú-Bihar'),
('Sárszentlőrinc', 'Tolna'),
('Sárvár', 'Vas'),
('Sásd', 'Baranya'),
('Sátoraljaújhely', 'Borsod-Abaúj-Zemplén'),
('Sellye', 'Baranya'),
('Seregélyes', 'Fejér'),
('Siklós', 'Baranya'),
('Simontornya', 'Tolna'),
('Siófok', 'Somogy'),
('Solt', 'Bács-Kiskun'),
('Soltvadkert', 'Bács-Kiskun'),
('Solymár', 'Pest'),
('Soponya', 'Fejér'),
('Sopron', 'Győr-Moson-Sopron'),
('Sükösd', 'Bács-Kiskun'),
('Sülysáp', 'Pest'),
('Sümeg', 'Veszprém'),
('Szabadbattyán', 'Fejér'),
('Szabadszállás', 'Bács-Kiskun'),
('Szany', 'Győr-Moson-Sopron'),
('Szarvas', 'Békés'),
('Szászvár', 'Baranya'),
('Százhalombatta', 'Pest'),
('Szécsény', 'Nógrád'),
('Szeged', 'Csongrád'),
('Szeghalom', 'Békés'),
('Szegvár', 'Csongrád'),
('Székesfehérvár', 'Fejér'),
('Szekszárd', 'Tolna'),
('Szendrő', 'Borsod-Abaúj-Zemplén'),
('Szentendre', 'Pest'),
('Szentes', 'Csongrád'),
('Szentgotthárd', 'Vas'),
('Szentistván', 'Borsod-Abaúj-Zemplén'),
('Szentlőrinc', 'Baranya'),
('Szerencs', 'Borsod-Abaúj-Zemplén'),
('Szigethalom', 'Pest'),
('Szigetszentmiklós', 'Pest'),
('Szigetvár', 'Baranya'),
('Szikszó', 'Borsod-Abaúj-Zemplén'),
('Szirmabesenyő', 'Borsod-Abaúj-Zemplén'),
('Szob', 'Pest'),
('Szolnok', 'Jász-Nagykun-Szolnok'),
('Szombathely', 'Vas'),
('Tab', 'Somogy'),
('Taksony', 'Pest'),
('Taktaharkány', 'Borsod-Abaúj-Zemplén'),
('Tamási', 'Tolna'),
('Tápiószecső', 'Pest'),
('Tápiószele', 'Pest'),
('Tápiószentmárton', 'Pest'),
('Tapolca', 'Veszprém'),
('Tardos', 'Komárom-Esztergom'),
('Tárnok', 'Pest'),
('Tarpa', 'Szabolcs-Szatmár-Bereg'),
('Tát', 'Komárom-Esztergom'),
('Tata', 'Komárom-Esztergom'),
('Tatabánya', 'Komárom-Esztergom'),
('Téglás', 'Hajdú-Bihar'),
('Telkibánya', 'Borsod-Abaúj-Zemplén'),
('Tét', 'Győr-Moson-Sopron'),
('Tihany', 'Veszprém'),
('Tiszaalpár', 'Bács-Kiskun'),
('Tiszabecs', 'Szabolcs-Szatmár-Bereg'),
('Tiszacsege', 'Hajdú-Bihar'),
('Tiszadob', 'Szabolcs-Szatmár-Bereg'),
('Tiszaföldvár', 'Jász-Nagykun-Szolnok'),
('Tiszafüred', 'Jász-Nagykun-Szolnok'),
('Tiszakécske', 'Bács-Kiskun'),
('Tiszalök', 'Szabolcs-Szatmár-Bereg'),
('Tiszalúc', 'Borsod-Abaúj-Zemplén'),
('Tiszaújváros', 'Borsod-Abaúj-Zemplén'),
('Tiszavasvári', 'Szabolcs-Szatmár-Bereg'),
('Tokaj', 'Borsod-Abaúj-Zemplén'),
('Tokod', 'Komárom-Esztergom'),
('Tolna', 'Tolna'),
('Tompa', 'Bács-Kiskun'),
('Tótkomlós', 'Békés'),
('Tököl', 'Pest'),
('Törökbálint', 'Pest'),
('Törökszentmiklós', 'Jász-Nagykun-Szolnok'),
('Tura', 'Pest'),
('Túrkeve', 'Jász-Nagykun-Szolnok'),
('Tuzsér', 'Szabolcs-Szatmár-Bereg'),
('Tyukod', 'Szabolcs-Szatmár-Bereg'),
('Újfehértó', 'Szabolcs-Szatmár-Bereg'),
('Újkígyós', 'Békés'),
('Újszász', 'Jász-Nagykun-Szolnok'),
('Üllő', 'Pest'),
('Vác', 'Pest'),
('Vaja', 'Szabolcs-Szatmár-Bereg'),
('Vajszló', 'Baranya'),
('Valkó', 'Pest'),
('Vámospércs', 'Hajdú-Bihar'),
('Várpalota', 'Veszprém'),
('Vásárosnamény', 'Szabolcs-Szatmár-Bereg'),
('Vasvár', 'Vas'),
('Vecsés', 'Pest'),
('Velence', 'Fejér'),
('Vép', 'Vas'),
('Veresegyház', 'Pest'),
('Verpelét', 'Heves'),
('Veszprém', 'Veszprém'),
('Vésztő', 'Békés'),
('Villány', 'Baranya'),
('Visegrád', 'Pest'),
('Vonyarcvashegy', 'Zala'),
('Záhony', 'Szabolcs-Szatmár-Bereg'),
('Zalaegerszeg', 'Zala'),
('Zalakaros', 'Zala'),
('Zalalövő', 'Zala'),
('Zalaszentgrót', 'Zala'),
('Zamárdi', 'Somogy'),
('Zámoly', 'Fejér'),
('Zirc', 'Veszprém'),
('Zsáka', 'Hajdú-Bihar'),
('Zsámbék', 'Pest');
insert into regio(nev, megye) values
('Észak-Magyarország', 'Borsod-Abaúj-Zemplén'),
('Észak-Magyarország', 'Heves'),
('Észak-Magyarország', 'Nógrád'),
('Észak-Alföld', 'Hajdú-Bihar'),
('Észak-Alföld', 'Jász-Nagykun-Szolnok'),
('Észak-Alföld', 'Szabolcs-Szatmár-Bereg'),
('Dél-Alföld', 'Bács-Kiskun'),
('Dél-Alföld', 'Békés'),
('Dél-Alföld', 'Csongrád'),
('Közép-Magyarország', 'Pest'),
('Közép-Magyarország', 'Budapest'),
('Közép-Dunántúl', 'Komárom-Esztergom'),
('Közép-Dunántúl', 'Fejér'),
('Közép-Dunántúl', 'Veszprém'),
('Nyugat-Dunántúl', 'Győr-Moson-Sopron'),
('Nyugat-Dunántúl', 'Vas'),
('Nyugat-Dunántúl', 'Zala'),
('Dél-Dunántúl', 'Baranya'),
('Dél-Dunántúl', 'Somogy'),
('Dél-Dunántúl', 'Tolna');
insert into kiosztas(frekvencia, teljesitmeny, csatorna, adohely, cim) values
('87.6', '7.6', 'Neo FM ', 'Győr', 'Szabadhegy '),
('87.6', '0.5', 'Gong Rádió', 'Csongrád', 'nincs adat'),
('87.6', '  ', 'Kontakt Rádió ', 'Budapest', 'Terézváros '),
('87.8', '0.001', 'ZsebRádió ', 'Halásztelek ', 'nincs adat'),
('87.8', '0.0006', 'Remete Rádió ', 'Pécs', 'Istenkút '),
('87.8', '0.0005', 'Origóház Rádió ', 'Pécs', 'Mecsekszabolcs '),
('87.8', '0.001', 'Rádió Sansz - A lehetőség! ', 'Székesfehérvár ', 'nincs adat'),
('87.9', '0.2', 'Dió Rádió ', 'Hatvan ', 'nincs adat'),
('87.9', '0.16', 'Rádió 1 ', 'Sárbogárd ', 'nincs adat'),
('88', '0.125', 'N-Joy 88,0', 'Marcali ', 'nincs adat'),
('88', '0.002', 'Méliusz Rádió ', 'Debrecen ', 'nincs adat'),
('88', '0.007', 'Berettyó Night ', 'Berettyóújfalu ', 'nincs adat'),
('88', '0.001', 'Alfa Rádió ', 'Balkány ', 'nincs adat'),
('88', '  ', 'Karcag FM ', 'Karcag ', 'nincs adat'),
('88.1', '1', 'Rise FM ', 'Budapest', 'Gellért-hegy '),
('88.1', '  ', '  ', 'Győr ', 'nincs adat'),
('88.2', '0.2', 'Mária Rádió ', 'Kiskunmajsa ', 'nincs adat'),
('88.2', '0.05', 'Pelso Rádió ', 'Balatonföldvár ', 'nincs adat'),
('88.3', '5', 'MR1-Kossuth Rádió ', 'Tokaj', 'Nagy-kopasz '),
('88.3', '1', 'Mária Rádió ', 'Komárom ', 'nincs adat'),
('88.3', '0.1', 'Juventus Rádió', 'Mezőkovácsháza ', 'nincs adat'),
('88.4', '2', 'Neo FM ', 'Csengőd', 'Kiskőrös '),
('88.4', '0.3', 'Nyugat Rádió', 'Szombathely ', 'nincs adat'),
('88.6', '0.1', 'Juventus Rádió', 'Orosháza ', 'nincs adat'),
('88.6', '0.3', 'Tenkes Rádió ', 'Siklós ', 'nincs adat'),
('88.7', '0.3', 'Parti Rádió ', 'Tiszafüred ', 'nincs adat'),
('88.7', '0.24', 'Gong Rádió Baja ', 'Baja ', 'nincs adat'),
('88.7', '0.001', 'Triangulum Rádió ', 'Őriszentpéter ', 'nincs adat'),
('88.7', '0.002', 'Vértes Rádió ', 'Zámoly ', 'nincs adat'),
('88.8', '0.1', 'Rádió C ', 'Budapest', 'Széchenyi-hegy '),
('88.8', '0.1', 'Klubrádió ', 'Ajka ', 'nincs adat'),
('88.8', '0.5', 'Rádió TOP ', 'Kazincbarcika ', 'nincs adat'),
('88.9', '0.3', 'Rádió 1 Start ', 'Békéscsaba ', 'nincs adat'),
('88.9', '0.2', 'Klubrádió Gyöngyös ', 'Gyöngyös', 'Sár-hegy '),
('88.9', '0.1', 'N-Joy 88,9', 'Zalaegerszeg ', 'nincs adat'),
('88.9', '0.001', 'Muzik Rádió ', 'Székesfehérvár ', 'nincs adat'),
('89', '1', 'MR2-Petőfi Rádió ', 'Debrecen', 'Pallag '),
('89', '0.1', 'Ezerjó Rádió ', 'Mór ', 'nincs adat'),
('89.2', '0.05', 'Parti Rádió ', 'Abádszalók ', 'nincs adat'),
('89.4', '6.3', 'MR2-Petőfi Rádió ', 'Csávoly ', 'nincs adat'),
('89.5', '83', 'Juventus Rádió ', 'Budapest', 'Széchenyi-hegy '),
('89.5', '0.05', 'MR1-Kossuth Rádió ', 'Barcs ', 'nincs adat'),
('89.6', '0.2', 'Rádió 35 ', 'Tiszaújváros ', 'nincs adat'),
('89.6', '0.002', 'Mustár Rádió ', 'Nyíregyháza ', 'nincs adat'),
('89.8', '0.1', 'Bajai Rádió ', 'Baja ', 'nincs adat'),
('89.8', '0.2', 'Rádió Express 89,8 ', 'Sárospatak ', 'nincs adat'),
('89.9', '5', 'MR1-Kossuth Rádió ', 'Komádi ', 'nincs adat'),
('89.9', '0.05', 'MR1-Kossuth Rádió ', 'Salgótarján ', 'nincs adat'),
('89.9', '0.003', 'Puszta Rádió ', 'Kunszentmiklós ', 'nincs adat'),
('89.9', '0.001', 'Szóbeszéd Rádió Mártély ', 'Mártély ', 'nincs adat'),
('89.9', '0.002', 'Rákóczi Hírmondó ', 'Rákóczifalva ', 'nincs adat'),
('89.9', '0.001', 'Itt mi vagyunk! Rádió Mi ', 'Szeged ', 'nincs adat'),
('89.9', '0.001', 'Pont Rádió ', 'Mezőtúr ', 'nincs adat'),
('89.9', '0.003', 'Rádió Weekend ', 'Tótkomlós ', 'nincs adat'),
('89.9', '0.001', 'Rádió Smile ', 'Kiskunfélegyháza ', 'nincs adat'),
('90', '0.5', 'Friss Rádió ', 'Debrecen ', 'nincs adat'),
('90', '0.07', '  ', 'Várpalota ', 'nincs adat'),
('90.2', '8.3', 'Neo FM ', 'Nagykanizsa', 'Újudvar, Tukora '),
('90.2', '3', 'MR1-Kossuth Rádió ', 'Telkibánya', 'Nagy-hegy '),
('90.2', '0.1', 'Rádió 1 Orosháza ', 'Orosháza ', 'nincs adat'),
('90.3', '3', 'MR2-Petőfi Rádió ', 'Sárszentlőrinc', 'Úzd '),
('90.3', '0.6', 'Neo FM ', 'Szeged ', 'nincs adat'),
('90,3	0,4', 'Tilos Rádió ', 'Budapest', 'Változó ', 'nincs adat'),
('90.3', '0.1', 'Rádió Plusz ', 'Berettyóújfalu ', 'nincs adat'),
('90.4', '0.1', 'Európa Rádió ', 'Miskolc', 'Pereces '),
('90.4', '0.2', 'Európa Rádió Záhony ', 'Záhony ', 'nincs adat'),
('90.4', '0.2', 'Rádió 2000 ', 'Szolnok ', 'nincs adat'),
('90.4', '0.1', 'Gondola Rádió ', 'Velence', 'Meleg-hegy '),
('90.5', '0.8', 'Kék Duna Rádió', 'Komárom ', 'nincs adat'),
('90.5', '0.25', 'Juventus Rádió', 'Gyula ', 'nincs adat'),
('90.6', '1.25', 'Klubrádió ', 'Veszprém ', 'nincs adat'),
('90.6', '1', 'Szent István Rádió ', 'Sátoraljaújhely', 'Magas-hegy '),
('90.6', '0.25', 'Rádió 1 ', 'Pécs', 'Kertváros '),
('90.7', '28.2', 'MR3-Bartók Rádió ', 'Kékes ', 'nincs adat'),
('90.8', '0.1', 'MR1-Kossuth Rádió ', 'Hódmezővásárhely ', 'nincs adat'),
('90.8', '  ', 'MR1-Kossuth Rádió ', 'Hódmezővásárhely ', 'nincs adat'),
('90.9', '0.2', '90,9 Jazzy ', 'Budapest', 'Sas-hegy '),
('91', '0.01', 'István Király Rádió ', 'Győr', 'Bácsa '),
('91.1', '0.5', '  ', 'Nyíregyháza ', 'nincs adat'),
('91.1', '0.45', 'Alisca Rádió ', 'Szekszárd ', 'nincs adat'),
('91.1', '0.2', 'SUNSHINE Rádió Pilis ', 'Szentendre', 'Pismány-hegy '),
('91.1', '0.1', 'Sirius Rádió ', 'Kiskunfélegyháza ', 'nincs adat'),
('91.2', '0.1', 'Enjoy Rádió ', 'Kaposvár ', 'nincs adat'),
('91.3', '0.1', 'MR1-Kossuth Rádió ', 'Dunaújváros ', 'nincs adat'),
('91.4', '1.2', 'MR6-A Régió Rádiója - Debrecen ', 'Debrecen', 'Pallag '),
('91.4', '0.05', 'Mária Rádió ', 'Komló ', 'nincs adat'),
('91.4', '0.001', 'Domb Rádió Sellye ', 'Sellye ', 'nincs adat'),
('91.4', '0.001', 'Diák Rádió Szerencs ', 'Szerencs ', 'nincs adat'),
('91.5', '1', 'Kék Duna Rádió', 'Győr', 'Szabadhegy '),
('91.6', '6.8', 'Neo FM ', 'Vasvár', 'Hegyhátsál '),
('91.6', '1', 'MR1-Kossuth Rádió ', 'Szentes ', 'nincs adat'),
('91.6', '1', 'Fortuna Rádió ', 'Cece ', 'nincs adat'),
('91.7', '1.2', 'Kunság Rádió ', 'Kiskőrös ', 'nincs adat'),
('91.7', '0.1', 'Mária Rádió ', 'Pécel ', 'nincs adat'),
('91.8', '0.5', 'Szent István Rádió ', 'Eger', 'Nagy-Eged '),
('91.8', '0.2', 'Klubrádió ', 'Balatonfüred ', 'nincs adat'),
('91.8', '0.16', 'MR1-Kossuth Rádió ', 'Püspökladány ', 'nincs adat'),
('91.9', '1', 'MR1-Kossuth Rádió ', 'Sátoraljaújhely', 'Magas-hegy '),
('91.9', '0.004', 'Diák Rádió Edelény ', 'Edelény ', 'nincs adat'),
('92', '0.1', 'MR1-Kossuth Rádió ', 'Paks ', 'nincs adat'),
('92.1', '1', 'BBC-RFI ', 'Budapest', 'Széchenyi-hegy '),
('92.2', '0.1', 'Aktív Rádió ', 'Szolnok ', 'nincs adat'),
('92.2', '0.1', 'Klubrádió', 'Keszthely ', 'nincs adat'),
('92.2', '0.035', 'SuGo Rádió ', 'Baja ', 'nincs adat'),
('92.3', '1', 'MR1-Kossuth Rádió ', 'Székesfehérvár', 'Sóstó '),
('92.3', '0.3', 'Rádió 1 ', 'Debrecen ', 'nincs adat'),
('92.4', '0.001', 'Diósgyőr Rádió ', 'Miskolc', 'Diósgyőr '),
('92.4', '0.003', 'Rádió Egy 100 ', 'Százhalombatta ', 'nincs adat'),
('92.4', '0.003', 'Zöld Rádió ', 'Erdőkertes ', 'nincs adat'),
('92.4', '0.001', 'Rádió Füzes ', 'Füzesabony ', 'nincs adat'),
('92.4', '0.003', 'Diák Rádió Kazincbarcika ', 'Kazincbarcika ', 'nincs adat'),
('92.4', '0.001', 'Hernád Völgye Rádió', 'Aszaló ', 'nincs adat'),
('92.4', '0.0004', 'Rádió Eper ', 'Miskolc ', 'nincs adat'),
('92.4', '0.001', 'Zagyvan Rádió ', 'Hatvan ', 'nincs adat'),
('92.5', '0.316', 'Cegléd Rádió 88 ', 'Cegléd ', 'nincs adat'),
('92.5', '0.1', 'Kék Duna Rádió Győr ', 'Esztergom', 'Elő-hegy '),
('92.6', '1', 'Juventus Rádió ', 'Siófok ', 'nincs adat'),
('92.7', '50', 'MR2-Petőfi Rádió ', 'Tokaj', 'Nagy-kopasz '),
('92.7', '0.1', 'Klubrádió ', 'Pápa ', 'nincs adat'),
('92.8', '0.25', 'Tamási Rádió ', 'Bonyhád ', 'nincs adat'),
('92.9', '5', 'Magyar Katolikus Rádió', 'Budapest', 'Gellért-hegy '),
('92.9', '0.05', 'Party FM 92,9 Rádió ', 'Kiskunhalas ', 'nincs adat'),
('92.9', '0.1', 'Rádió Egerszeg ', 'Zalaegerszeg ', 'nincs adat'),
('93', '1', 'MR1-Kossuth Rádió ', 'Cegléd ', 'nincs adat'),
('93', '0.1', 'MR1-Kossuth Rádió ', 'Szombathely ', 'nincs adat'),
('93.1', '7.5', 'MR2-Petőfi Rádió ', 'Győr', 'Szabad-hegy '),
('93.1', '0.76', 'MR6-A Régió Rádiója - Szeged ', 'Szeged ', 'nincs adat'),
('93.1', '0.1', 'EL-DO Rádió ', 'Dunaújváros ', 'nincs adat'),
('93.2', '0.3', '  ', 'Ajka ', 'nincs adat'),
('93.3', '0.15', 'Rádió FM 95 Hajdúnánás ', 'Hajdúnánás ', 'nincs adat'),
('93.4', '1', 'Dabas Rádió ', 'Dabas ', 'nincs adat'),
('93.4', '0.2', 'Vár FM Kisvárda ', 'Kisvárda ', 'nincs adat'),
('93.5', '1', 'Klubrádió Debrecen ', 'Debrecen ', 'nincs adat'),
('93.5', '0.002', 'Fúzió Rádió ', 'Budapest', 'Újbuda'),
('93.5', '0.001', 'Kolumbusz Rádió ', 'Etyek', 'Botpuszta '),
('93.5', '0.002', 'Csobán Rádió ', 'Csobánka ', 'nincs adat'),
('93.6', '5', 'Rádió Express 93,6 ', 'Szikszó ', 'nincs adat'),
('93.6', '3', 'MR1-Kossuth Rádió ', 'Siófok', 'Balatonszabadi-Sóstó '),
('93.6', '0.1',	'Arany Rádió', 'Nagykőrös', 'nincs adat'),
('93.6', '0.1', 'Gong Rádió Nagykőrös',	'Nagykőrös', 'nincs adat'),
('93.6', '0.1', 'Pelikán Rádió', 'Gödöllő ', 'nincs adat'),
('93.7', '2.5', 'MR1-Kossuth Rádió ', 'Balassagyarmat', 'Szügy-Dezsőpuszta '),
('93.7', '0.1', 'Diórádió ', 'Heves ', 'nincs adat'),
('93.7', '0.005', 'Csillaghang Rádió ', 'Budapest', 'Budafok'),
('93.8', '0.4', 'Baranya Rádió ', 'Mohács ', 'nincs adat'),
('93.8', '0.2', '  ', 'Karcag ', 'nincs adat'),
('93.9', '65.6', 'MR2-Petőfi Rádió ', 'Kab-hegy ', 'nincs adat'),
('94', '0.8', 'Fortuna Rádió ', 'Bonyhád ', 'nincs adat'),
('94', '0.316', 'Szent István Rádió ', 'Hatvan ', 'nincs adat'),
('94.1', '0.5', 'Nap Rádió ', 'Sopron', 'Dalos-hegy '),
('94.1', '0.1', 'Mária Rádió ', 'Vác', 'Sződliget '),
('94.1', '0.5', 'Gong Rádió Solt ', 'Solt ', 'nincs adat'),
('94.2', '0.1', 'Mária Rádió ', 'Budapest', 'Sas-hegy '),
('94.2', '0.003', 'Rádió Ice ', 'Makó ', 'nincs adat'),
('94.2', '0.0004', 'Tisza Rádió ', 'Szeged ', 'nincs adat'),
('94.3', '12', 'MR2-Petőfi Rádió ', 'Nagykanizsa', 'Újudvar'),
('94.3', '6.3', 'MR1-Kossuth Rádió ', 'Szolnok ', 'nincs adat'),
('94.3', '0.05', 'Alisca Rádió ', 'Baja ', 'nincs adat'),
('94.4', '1', 'Gold FM Debrecen', 'Debrecen ', 'nincs adat'),
('94.4', '0.07', 'Torony Rádió ', 'Békés ', 'nincs adat'),
('94.5', '0.125', 'Juventus Rádió Kapuvár ', 'Kapuvár ', 'nincs adat'),
('94.5', '0.1', 'Fehérvár Rádió ', 'Székesfehérvár', 'Öreghegy '),
('94.6', '3', 'MR1-Kossuth Rádió ', 'Aggtelek', 'Szár-hegy '),
('94.6', '0.1', 'Rádió 1 ', 'Veszprém ', 'nincs adat'),
('94.6', '0.1', 'Mária Rádió ', 'Pécs ', 'nincs adat'),
('94.7', '0.1', 'Rádió Plusz ', 'Derecske ', 'nincs adat'),
('94.8', '77.6', 'MR2-Petőfi Rádió ', 'Budapest', 'Széchenyi-hegy '),
('94.8', '0.15', 'N-Joy 94,8 Letenye ', 'Letenye ', 'nincs adat'),
('94.9', '0.6', 'Klassz Rádió  ', 'Szeged ', 'nincs adat'),
('95', '0.5', 'Rádió FM 95 ', 'Debrecen ', 'nincs adat'),
('95', '1', 'MR1-Kossuth Rádió ', 'Mosonmagyaróvár ', 'nincs adat'),
('95', '0.1', 'MR1-Kossuth Rádió ', 'Bácsalmás ', 'nincs adat'),
('95.1', '1.74', 'MR2-Petőfi Rádió ', 'Csengőd', 'Kiskőrös '),
('95.1', '1', 'Szent István Rádió ', 'Miskolc', 'Pereces '),
('95.1', '0.001', 'Karzat Rádió Sárospatak ', 'Sárospatak ', 'nincs adat'),
('95.2', '0.1', 'Juventus Rádió Szarvas ', 'Szarvas ', 'nincs adat'),
('95.3', '0.93', 'Klubrádió ', 'Budapest', 'Széchenyi-hegy '),
('95.4', '1', 'Rádió 88 ', 'Szeged ', 'nincs adat'),
('95.4', '5', 'Rádió Express 95,4 ', 'Encs ', 'nincs adat'),
('95.5', '20', 'Neo FM ', 'Kékes ', 'nincs adat'),
('95.6', '0.91', 'Rádió FUN ', 'Debrecen ', 'nincs adat'),
('95.6', '0.126', 'Kanizsa Rádió ', 'Nagykanizsa', 'Újudvar'),
('95.6', '0.1', 'MR1-Kossuth Rádió ', 'Veszprém ', 'nincs adat'),
('95.7', '1', 'Gazdasági Rádió 95,7 ', 'Balassagyarmat ', 'nincs adat'),
('95.7', '0.2', 'Rádió Plusz ', 'Szentes ', 'nincs adat'),
('95.8', '2', 'Infó Rádió ', 'Budapest', 'Széchenyi-hegy '),
('95.9', '25.1', 'Neo FM ', 'Pécs', 'Misina-tető '),
('95.9', '0.2', 'Új Juventus ', 'Kazincbarcika ', 'nincs adat'),
('96', '0.25', 'MR1-Kossuth Rádió ', 'Gyula ', 'nincs adat'),
('96', '0.2', 'MR1-Kossuth Rádió ', 'Sárvár ', 'nincs adat'),
('96.2', '0.1', 'MR1-Kossuth Rádió ', 'Eger ', 'nincs adat'),
('96.3', '0.3', 'Fortuna Rádió ', 'Paks ', 'nincs adat'),
('96.3', '0.25', 'Új Juventus ', 'Miskolc', 'Avas '),
('96.3', '0.003', 'Rádio Studio ', 'Zalaegerszeg ', 'nincs adat'),
('96.4', '2.5', 'Roxy Rádió ', 'Budapest', 'Gellért-hegy '),
('96.4', '0.58', 'Rádió 1 ', 'Győr ', 'nincs adat'),
('96.4', '0.3', 'Rádió Törökszentmiklós ', 'Törökszentmiklós ', 'nincs adat'),
('96.4', '0.1', 'MR1-Kossuth Rádió ', 'Pápa ', 'nincs adat'),
('96.5', '2', 'Gong Rádió ', 'Kecskemét ', 'nincs adat'),
('96.5', '0.1', 'Isis Rádió ', 'Sárvár ', 'nincs adat'),
('96.6', '0.3', 'Yo! Rádió Sárbogard ', 'Sárbogárd ', 'nincs adat'),
('96.6', '0.001', 'Haraszti Hangja Rádió ', 'Dunaharaszti ', 'nincs adat'),
('96.7', '37.1', 'MR2-Petőfi Rádió ', 'Komádi ', 'nincs adat'),
('96.7', '6.3', 'Neo FM ', 'Csávoly ', 'nincs adat'),
('96.7', '3', 'MR1-Kossuth Rádió ', 'Kaposvár', 'Rómahegy '),
('96.7', '0.3', 'Klubrádió ', 'Tatabánya', 'Árpád Hotel '),
('96.8', '8.9', 'Neo FM ', 'Sopron', 'Dalos-hegy '),
('96.8', '0.2', 'Árkádia Rádió ', 'Makó ', 'nincs adat'),
('96.8', '1', 'Rádió 17 Rákosmente ', 'Budapest', 'XVII. Kerület'),
('96.8', '0.001', 'Rádió Twist ', 'Debrecen ', 'nincs adat'),
('97', '0.0005', 'Első Pesti Egyetemi Rádió (EPER) ', 'Budapest', 'ELTE'),
('97', '0.01', 'Kis-Duna Rádió ', 'Áporka ', 'nincs adat'),
('97.1', '5.6', 'Neo FM ', 'Miskolc', 'Avas '),
('97.1', '0.2', 'Rádió Szombathely ', 'Szombathely ', 'nincs adat'),
('97.1', '0.5', 'Yo! Rádió ', 'Várpalota ', 'nincs adat'),
('97.1', '0.0008', 'Periszkóp Rádió ', 'Pécs', 'nincs adat'),
('97.1', '0.003', 'Kerepes Rádió ', 'Kerepes ', 'nincs adat'),
('97.2', '0.05', 'Rádió Gyömrő 97,2 MHz ', 'Gyömrő ', 'nincs adat'),
('97.2', '0.05', 'Gong Rádió Gyömrő ', 'Gyömrő ', 'nincs adat'),
('97.3', '1.25', 'Abszolút Rádió ', 'Göd ', 'nincs adat'),
('97.3', '1', 'MR1-Kossuth Rádió ', 'Békéscsaba ', 'nincs adat'),
('97.4', '1', 'Rádió Antritt Dunaföldvár ', 'Dunaföldvár ', 'nincs adat'),
('97.4', '0.2', '  ', 'Esztergom ', 'nincs adat'),
('97.5', '50.1', 'Neo FM ', 'Tokaj', 'Nagy-kopasz '),
('97.5', '0.15', 'K1 Rádió ', 'Kaposvár ', 'nincs adat'),
('97.5', '0.4', 'Mária Rádió ', 'Dabas ', 'nincs adat'),
('97.6', '0.8', 'Rádió 7 Hódmezővásárhely ', 'Hódmezővásárhely ', 'nincs adat'),
('97.7', '1', 'Klubrádió ', 'Kecskemét ', 'nincs adat'),
('97.7', '0.8', 'MR1-Kossuth Rádió ', 'Kazincbarcika ', 'nincs adat'),
('97.7', '0.1', 'Rádió Jászberény ', 'Jászberény ', 'nincs adat'),
('97.7', '0.1', 'Rádió Szentgotthárd/Monošter ', 'Felsőszölnök', 'Kakas-domb '),
('97.8', '0.1', 'Rádió Radír ', 'Tatabánya', 'Kő-hegy '),
('97.9', '10', 'MR1-Kossuth Rádió ', 'Karcag ', 'nincs adat'),
('97.9', '0.01', 'Berettyó Rádió ', 'Berettyóújfalu ', 'nincs adat'),
('97.9', '0.01', 'Campus Rádió ', 'Nyíregyháza', 'Jósaváros '),
('97.9', '0.001', '4-SSSS Rádió ', 'Téglás ', 'nincs adat'),
('97.9', '0.001', 'Galaxis Rádió ', 'Heves ', 'nincs adat'),
('98', '0.138', 'Civil Rádió ', 'Budapest', 'Lágymányos '),
('98', '0.004', 'Abakusz Rádió ', 'Hajdúböszörmény ', 'nincs adat'),
('98', '0.001', 'Best of Rádió ', 'Tiszavasvári ', 'nincs adat'),
('98.1', '0.1', 'Klubrádió ', 'Esztergom', 'Elő-hegy '),
('98.2', '7.5', 'MR2-Petőfi Rádió ', 'Vasvár', 'Hegyhátsál '),
('98.2', '0.1', 'MR1-Kossuth Rádió ', 'Túrkeve ', 'nincs adat'),
('98.3', '5.6', 'Klassz Rádió  ', 'Miskolc', 'Avas '),
('98.4', '0.05', 'HA-JÓ Rádió ', 'Vaja ', 'nincs adat'),
('98.6', '1.2', 'Rádió Café ', 'Budapest', 'Széchenyi-hegy '),
('98.7', '0.8', 'N-Joy 98,7 Dombóvár ', 'Dombóvár ', 'nincs adat'),
('98.8', '32.4', 'MR2-Petőfi Rádió ', 'Szentes ', 'nincs adat'),
('98.8', '0.002', 'Berzsenyi Rádió ', 'Szombathely ', 'nincs adat'),
('98.8', '0.003', 'Rádió Cell ', 'Celldömölk ', 'nincs adat'),
('98.9', '1', 'N-Joy 98,9 Szigetvár ', 'Szigetvár ', 'nincs adat'),
('98.9', '0.32', 'Rise FM ', 'Tihany ', 'nincs adat'),
('98.9', '0.35', 'Rádió Fun ', 'Hajdúböszörmény ', 'nincs adat'),
('98.9', '0.1', 'Mária Rádió ', 'Gyál ', 'nincs adat'),
('98.9', '0.01', 'Rádió Avas ', 'Miskolc ', 'nincs adat'),
('98.9', '0.01', 'Ózdi Diák Rádió ', 'Ózd ', 'nincs adat'),
('98.9', '0.001', 'Rakamaz FM ', 'Rakamaz ', 'nincs adat'),
('99', '0.5', 'MR1-Kossuth Rádió ', 'Szekszárd ', 'nincs adat'),
('99.1', '0.1', 'Gerilla Rádió 99,1 ', 'Dunaújváros ', 'nincs adat'),
('99.2', '0.631', 'Vörösmarty Rádió ', 'Székesfehérvár', 'Öreghegy '),
('99.4', '0.1', 'SUNSHINE Rádió Nyíregyháza ', 'Nyíregyháza ', 'nincs adat'),
('99.4', '0.25', 'Rádió 1 ', 'Komló ', 'nincs adat'),
('99.4', '0.2', 'MR1-Kossuth Rádió ', 'Szeghalom ', 'nincs adat'),
('99.4', '0.1', 'Helikon Rádió ', 'Keszthely ', 'nincs adat'),
('99.5', '8.9', 'MR2-Petőfi Rádió ', 'Sopron', 'Dalos-hegy '),
('99.5', '5', 'Rádió Q ', 'Budapest', 'Gellért-hegy '),
('99.5', '0.05', 'Új Juventus ', 'Ózd ', 'nincs adat'),
('99.5', '0.2', '  ', 'Fehérgyarmat ', 'nincs adat'),
('99.5', '0.005', 'Origó Rádió Miskolc ', 'Miskolc ', 'nincs adat'),
('99.6', '1.25', 'Gong Rádió Kecel FM 99,6 MHz ', 'Kecel ', 'nincs adat'),
('99.7', '1.38', 'MR1-Kossuth Rádió ', 'Debrecen', 'Pallag '),
('99.8', '0.32', 'MR1-Kossuth Rádió ', 'Kékes ', 'nincs adat'),
('99.8', '0.4', 'Rádió 8 Körmend ', 'Körmend ', 'nincs adat'),
('99.9', '1', 'Kapos Rádió ', 'Kaposvár ', 'nincs adat'),
('100', '0.1', 'Korona Rádió Kalocsa ', 'Kalocsa ', 'nincs adat'),
('100', '0.94', 'Rádió Aktív FM 100,0 MHz ', 'Sátoraljaújhely', 'Magas-hegy '),
('100.1', '0.57', '  ', 'Győr ', 'nincs adat'),
('100.2', '2', 'Rádió Plusz ', 'Szeged ', 'nincs adat'),
('100.3', '1', 'Lánchíd Rádió ', 'Budapest', 'SOTE '),
('100.4', '34.7', 'Neo FM ', 'Szentes ', 'nincs adat'),
('100.4', '0.1', 'Rádió Focus ', 'Salgótarján ', 'nincs adat'),
('100.5', '67.6', 'Klassz Rádió  ', 'Kab-hegy ', 'nincs adat'),
('100.5', '1', '  ', 'Nyíregyháza ', 'nincs adat'),
('100.6', '3', 'Mária Rádió ', 'Telkibánya ', 'nincs adat'),
('100.6', '0.25', 'Rádió Fun ', 'Hajdúszoboszló ', 'nincs adat'),
('100.7', '1', 'Gazdasági Rádió 100,7 ', 'Eger ', 'nincs adat'),
('100.7', '0.1', 'Lajta Rádió ', 'Mosonmagyaróvár ', 'nincs adat'),
('100.8', '79.4', 'Neo FM ', 'Budapest', 'Széchenyi-hegy '),
('100.9', '0.25', 'Juventus Rádió Békéscsaba ', 'Békéscsaba ', 'nincs adat'),
('100.9', '0.1', 'Villány Rádió ', 'Villány ', 'nincs adat'),
('101.1', '1', 'Klassz Rádió  ', 'Debrecen', 'Pallag '),
('101.2', '0.2', 'Mediterrán Rádió ', 'Pécs ', 'nincs adat'),
('101.2', '2', 'MR6-A Régió Rádiója Debrecen ', 'Szolnok ', 'nincs adat'),
('101.3', '0.1', 'Rádió 6 FM 101,3 ', 'Érd ', 'nincs adat'),
('101.3', '1', 'Rádió Eger ', 'Eger', 'Almagyar-domb '),
('101.3', '0.05', 'Juventus Rádió ', 'Fonyód ', 'nincs adat'),
('101.4', '7.6', 'Klassz Rádió  ', 'Győr', 'Szabadhegy '),
('101,4	0,001', 'Helló Rádió ', 'Budapest', 'XIV. kerület ', 'nincs adat'),
('101.5', '3', 'Neo FM ', 'Sárszentlőrinc', 'Úzd '),
('101.6', '21.9', 'Klassz Rádió  ', 'Komádi ', 'nincs adat'),
('101.6', '0.5', 'MR1-Kossuth Rádió ', 'Sopron', 'Dalos-hegy '),
('101.7', '2', 'MR6-A Régió Rádiója-Pécs ', 'Pécs', 'Misina-tető '),
('101.7', '0.05', 'DióRádió ', 'Gyöngyös', 'Sár-hegy '),
('101.7', '0.003', 'Rádió Kistarcsa ', 'Kistarcsa ', 'nincs adat'),
('101.8', '1', 'Rádió 1 ', 'Székesfehérvár', 'Sóstó '),
('101.8', '0.1', 'Yo! Rádió ', 'Tapolca ', 'nincs adat'),
('101.8', '0.1', 'Rádió Express 101,8 ', 'Tokaj', 'Nagy-kopasz '),
('101.8', '0.003', 'Zöld hullám Rádió ', 'Piliscsaba ', 'nincs adat'),
('101.8', '0.002', 'Taks Rádió ', 'Taksony ', 'nincs adat'),
('101.9', '2', 'MR1-Kossuth Rádió ', 'Szeged ', 'nincs adat'),
('101.9', '1', 'Tamási Rádió ', 'Tamási ', 'nincs adat'),
('101.9', '0.16', 'Rádió 1 ', 'Eger ', 'nincs adat'),
('102', '22.4', 'Klassz Rádió  ', 'Sopron', 'Dalos-hegy '),
('102.1', '0.74', '102,1 Sztár Rádió ', 'Budapest', 'Széchenyi-hegy '),
('102.1', '0.5', 'Európa Rádió Mezőkövesd ', 'Mezőkövesd ', 'nincs adat'),
('102.2', '0.5', 'Aktív Rádió ', 'Tiszakécske ', 'nincs adat'),
('102.3', '3.16', 'MR1-Kossuth Rádió ', 'Kab-hegy ', 'nincs adat'),
('102.3', '1.4', 'MR6-A Régió Rádiója-Miskolc ', 'Miskolc', 'Avas '),
('102.4', '  ', 'MR1-Kossuth Rádió ', 'Kunszentmiklós ', 'nincs adat'),
('102.5', '0.48', 'Gold FM Tatabánya ', 'Tatabánya', 'Árpád Hotel '),
('102.6', '0.3', 'MR1-Kossuth Rádió ', 'Nyíregyháza ', 'nincs adat'),
('102.6', '0.5', 'N-Joy 102,6 Kaposvár ', 'Kaposvár ', 'nincs adat'),
('102.6', '0.1', 'MR1-Kossuth Rádió ', 'Zalaegerszeg', 'Bazita '),
('102.7', '30.2', 'MR2-Petőfi Rádió ', 'Kékes ', 'nincs adat'),
('102.7', '0.95', 'Aqua Rádió Barcs ', 'Barcs ', 'nincs adat'),
('102.7', '0.1', 'MR1-Kossuth Rádió ', 'Kiskunhalas ', 'nincs adat'),
('102.9', '0.5', 'Rádió 24 ', 'Dunaújváros ', 'nincs adat'),
('102.9', '0.002', 'FeZen Rádió ', 'Székesfehérvár ', 'nincs adat'),
('103', '38.9', 'Neo FM ', 'Komádi ', 'nincs adat'),
('103', '1', 'Sztár FM ', 'Miskolc', 'Avas '),
('103.1', '0.1', 'OXYGEN FM', 'Győr', 'Erzsébetliget '),
('103.2', '0.3', 'Európa Rádió Kisújszállás ', 'Kisújszállás ', 'nincs adat'),
('103.3', '81.3', 'Klassz Rádió  ', 'Budapest', 'Széchenyi-hegy '),
('103.5', '50.1', 'Klassz Rádió  ', 'Tokaj', 'Nagy-kopasz '),
('103.6', '5', 'MR1-Kossuth Rádió ', 'Vasvár', 'Hegyhátsál '),
('103.7', '49.5', 'MR2-Petőfi Rádió ', 'Pécs', 'Misina-tető '),
('103.8', '5', 'MR1-Kossuth Rádió ', 'Miskolc', 'Avas '),
('103.8', '0.05', 'MR1-Kossuth Rádió ', 'Letenye ', 'nincs adat'),
('103.9', '5', 'Rádió 1 ', 'Budapest', 'Gellért-hegy '),
('103.9', '1', 'Retro FM ', 'Nyíregyháza ', 'nincs adat'),
('104', '1', 'Csaba Rádió ', 'Békéscsaba ', 'nincs adat'),
('104.2', '0.05', 'Mária Rádió ', 'Piliscsaba ', 'nincs adat'),
('104.6', '5.1', 'MR2-Petőfi Rádió ', 'Szeged ', 'nincs adat'),
('104.6', '5', 'MR1-Kossuth Rádió ', 'Pécs', 'Misina-tető '),
('104.6', '0.8', '  ', 'Debrecen ', 'nincs adat'),
('104.6', '0.6', 'Corvinus Rádió ', 'Sopron', 'Dalos-hegy '),
('104.7', '26.9', 'Klassz Rádió  ', 'Kékes ', 'nincs adat'),
('104.7', '20.4', 'MR3-Bartók Rádió ', 'Nagykanizsa', 'Újudvar, Tukora '),
('104.8', '0.3', 'Budaörs Rádió ', 'Budaörs ', 'nincs adat'),
('104.9', '1', 'MR1-Kossuth Rádió ', 'Kecskemét ', 'nincs adat'),
('104.9', '0.81', 'Mária Rádió ', 'Dömös ', 'nincs adat'),
('105', '69.5', 'MR3-Bartók Rádió ', 'Kab-hegy ', 'nincs adat'),
('105', '0.05', 'MR1-Kossuth Rádió ', 'Ózd ', 'nincs adat'),
('105.1', '30', 'MR3-Bartók Rádió ', 'Komádi ', 'nincs adat'),
('105.1', '0.78', 'Rádió Antritt ', 'Szekszárd ', 'nincs adat'),
('105.2', '5.2', 'MR1-Kossuth Rádió ', 'Rábaszentandrás ', 'nincs adat'),
('105.3', '81.3', 'MR3-Bartók Rádió ', 'Budapest', 'Széchenyi-hegy '),
('105.4', '0.05', 'MR1-Kossuth Rádió ', 'Battonya ', 'nincs adat'),
('105.4', '0.003', 'Rádió X ', 'Hódmezővásárhely ', 'nincs adat'),
('105.4', '0.003', 'Rádió Szarvas ', 'Szarvas ', 'nincs adat'),
('105.5', '50.1', 'Klassz Rádió  ', 'Pécs', 'Misina-tető '),
('105.5', '50', 'MR3-Bartók Rádió ', 'Tokaj', 'Nagy-kopasz '),
('105.6', '10', 'MR1-Kossuth Rádió ', 'Gerecse ', 'nincs adat'),
('105.7', '2.2', 'MR3-Bartók Rádió ', 'Szeged ', 'nincs adat'),
('105.9', '5', 'MR1-Kossuth Rádió ', 'Fehérgyarmat', 'Penyige '),
('105.9', '3.2', 'Gazdasági Rádió ', 'Budapest', 'Gellért-hegy '),
('105.9', '3', 'MR3-Bartók Rádió ', 'Csengőd', 'Kiskőrös '),
('106', '0.74', 'Rádió Max ', 'Debrecen ', 'nincs adat'),
('106.1', '0.1', 'Rádió Szentes ', 'Szentes ', 'nincs adat'),
('106.3', '0.2', 'Part Rádió ', 'Balatonalmádi ', 'nincs adat'),
('106.3', '0.1', 'Mária Rádió ', 'Monor ', 'nincs adat'),
('106.4', '1', 'MR1-Kossuth Rádió ', 'Győr', 'Szabadhegy '),
('106.4', '0.05', 'MR1-Kossuth Rádió ', 'Tiszakécske ', 'nincs adat'),
('106.5', '1', 'Alisca Rádió ', 'Dunaföldvár ', 'nincs adat'),
('106.5', '1', 'Gold FM Miskolc', 'Miskolc', 'Avas '),
('106.6', '1', 'MR3-Bartók Rádió ', 'Debrecen', 'Pallag '),
('106.6', '0.1', 'Rádió Szentgotthárd', 'Szentgotthárd', 'Zsida-hegy '),
('106.7', '5', 'MR1-Kossuth Rádió ', 'Nagykanizsa', 'Újudvar, Tukora '),
('106.8', '7.4', 'MR3-Bartók Rádió ', 'Győr', 'Szabadhegy '),
('106.9', '3', 'MR3-Bartók Rádió ', 'Sárszentlőrinc', 'Úzd '),
('106.9', '3', 'MR3-Bartók Rádió ', 'Vasvár', 'Hegyhátsál '),
('106.9', '1', 'DióRádió FM 106.9 ', 'Eger ', 'nincs adat'),
('107', '0.275', 'Kék Duna Rádió Győr ', 'Tatabánya', 'Kő-hegy '),
('107', '0.8', 'Rádió 7 Kistelek ', 'Kistelek ', 'nincs adat'),
('107', '0.5', 'Lakihegy Rádió ', 'Szigetszentmiklós ', 'nincs adat'),
('107.2', '70.8', 'Neo FM ', 'Kab-hegy ', 'nincs adat'),
('107.3', '34.7', 'MR3-Bartók Rádió ', 'Szentes ', 'nincs adat'),
('107.3', '0.01', 'Cool FM ', 'Budapest', 'Gyáli út '),
('107.3', '0.005', 'Tavirózsa Rádió ', 'Veresegyház ', 'nincs adat'),
('107.4', '0.5', '  ', 'Szombathely ', 'nincs adat'),
('107.4', '0.31', '  ', 'Nyíregyháza ', 'nincs adat'),
('107.4', '0.001', 'Gorba Rádió ', 'Tardos ', 'nincs adat'),
('107.5', '1.4', 'MR3-Bartók Rádió ', 'Miskolc', 'Avas '),
('107.5', '1', 'Alisca Rádió ', 'Paks ', 'nincs adat'),
('107.6', '10', 'MR3-Bartók Rádió ', 'Pécs', 'Misina-tető '),
('107.8', '83.2', 'MR1-Kossuth Rádió ', 'Budapest', 'Széchenyi-hegy '),
('107.9', '6.9', 'MR3-Bartók Rádió ', 'Sopron', 'Dalos-hegy');
